// CMS ACTIONS
export const FETCH_CMS_ENDPOINTS = "FETCH_CMS_ENDPOINTS";
export const RECEIVE_CMS_ENDPOINTS = "RECEIVE_CMS_ENDPOINTS";
export const FETCH_CMS = "FETCH_CMS";
export const RECEIVE_CMS = "RECEIVE_CMS";
export const PARSE_CMS = "PARSE_CMS";
export const RECEIVE_PARSED_CMS = "RECEIVE_PARSED_CMS";
export const SET_CMS_STATUS = "SET_CMS_STATUS";
export const SET_CMS_ERROR = "SET_CMS_ERROR";

// NAV ACTIONS
export const SET_HOME_ISOPEN = "SET_HOME_ISOPEN";
export const SET_HOME_TRANSFORM = "SET_HOME_TRANSFORM";
export const SET_WEBAMP_ISOPEN = "SET_WEBAMP_ISOPEN";
export const SET_WEBAMP_TRANSFORM = "SET_WEBAMP_TRANSFORM";
export const FETCH_PAGES_FOR_NAV = "FETCH_PAGES_FOR_NAV";
export const SET_PAGES_FOR_NAV = "SET_PAGES_FOR_NAV";